version: '2'
services:
    smppsimulator-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        command: mongos --configdb smppsimulator-mongodb-config
    smppsimulator-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    smppsimulator-mongodb-config:
        image: mongo:3.6.3
        container_name: smppsimulator-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
